#!/bin/sh
# Gradle wrapper script
# Run: ./gradlew assembleDebug
# This file should be generated by "gradle wrapper" command
# For now, use Android Studio to sync and build the project
exec gradle "$@"
